### ISSUE TITLE
determine workshop environment

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#1]
Options:
- Docker Compose
- [OSGeoLive](https://live.osgeo.org)
  - would need recent pygeoapi version
  - depends on release schedule
- [Gitpod](https://gitpod.io)
- [Kasm](https://www.kasmweb.com)
- other options?

Considerations
- will need various backends (ES, PostgreSQL)

cc @geopython/diving-into-pygeoapi-team for comment/recommendation.

**Comment by tomkralidis** [comment]
Note: in discussion with @kalxas, given we need the latest pygeoapi, this may not be on OSGeoLive in time for the event.

What about a Docker Compose setup?

**Comment by francbartoli** [comment]
It is still good @tomkralidis

**Comment by justb4** [comment]
Does "Docker Compose" imply a Docker installation on participants' machines? Or Docker Compose within OSGeoLive?

**Comment by tomkralidis** [comment]
Good question, deferring to @kalxas.

**Comment by kalxas** [comment]
We decided in the meeting to go with docker-compose

**Comment by tomkralidis** [comment]
As well:
-  we will also provide a docker cheatsheet for the purpose of the workshop with commonly used commands
- we will also provide QGIS install instructions/pointers (which will help for client exercises)

**Comment by PascalLike** [comment]
Do you think this docker-compose could be good as a starting point?

https://github.com/geopython/pygeoapi/tree/master/docker/examples/elastic

**Comment by doublebyte1** [comment]
On today's meeting we discussed: 
- Going ahead with docker & docker-compose, so we can remove the instructions for installing/compiling pygeoapi from scratch (we can provide a link to the [pygeoapi documentation](https://docs.pygeoapi.io/en/latest/installation.html), if people are interested.
- Using a single [docker-compose file](https://github.com/geopython/diving-into-pygeoapi/blob/main/workshop/docker/docker-compose.yml) for all the standards, and commenting everything in the beginning, apart from the minimal example. Then people can uncomment the sections incrementally, and end up with a pygeoapi installation that serves data in different standards. The same approach can be followed for the docker.config, as seen [here](https://github.com/geopython/diving-into-pygeoapi/blob/main/workshop/docker/pygeoapi/docker.config.yml).
- Providing instructions to install [QGIS](https://qgis.org/en/site/forusers/download.html) and other clients we are going to use during the workshop.
