### ISSUE TITLE
add bridge provider exercises

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#109]
- OGC API - Records: CSWFacade
- OGC API - Maps: WMSFacade
- OGC API - Features; WFS

**Comment by doublebyte1** [comment]
A bridge section was added [here](https://dive.pygeoapi.io/advanced/bridges/) that contains exercises for OGC API Maps and Features. 

@krishnaglodha We still miss exercises for: OGC API Records and SensorThings API. Here are some relevant links:

Information about the CSW Facade: https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-records.html#cswfacade

SensorThings proxy documentation: https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html#sensorthings-api
Docker example for SensorThings proxy: https://github.com/geopython/pygeoapi/tree/master/docker/examples/sensorthings
