### ISSUE TITLE
add STA section into features exercise

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#112]
- add SensorThings API section to Exercise 2

cc @doublebyte1

**Comment by doublebyte1** [comment]
@tomkralidis maybe this will be a bit confusing, as we would need to [setup the bridge](https://dive.pygeoapi.io/advanced/bridges/#publishing-sensorthings-api-as-ogc-api-features) prior to this exercise. I rather refer to the client section of features, once they have the bridge running, and encourage them to reproduce the client access steps with the new endpoint.
