### ISSUE TITLE
add Client access section to Exercise 7 EDR

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#113]
@krishnaglodha  add "Client Access" section at the end of [this](https://dive.pygeoapi.io/publishing/ogcapi-edr/) module with examples of accessing OGC API - EDR with a client.

A list of existing clients is available here: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/implementations/clients

**Comment by doublebyte1** [comment]
@krishnaglodha not sure if you are still working on this, but there are some examples of clients here: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/implementations/clients

**Comment by tomkralidis** [comment]
PR in #133.
