### ISSUE TITLE
Create a custom domain and auto-publish the workshops docs there

### ISSUE THREAD

**Issue by justb4** [geopython/diving-into-pygeoapi#13]
In follow up of #12: need to:

* auto-publish the docs, like the [Geonovum Example](https://github.com/Geonovum/ogc-api-testbed/blob/main/.github/workflows/deploy.docs.yml) and [gh-pages](https://github.com/Geonovum/ogc-api-testbed/tree/gh-pages)
* in DNS: create a subdomain to host the WS (mk)docs, e.g. short: `ws.pygeoapi.io` or `dive.pygeoapi.io`
* in DNS: do the `CNAME DNS` trick
* in GH repo: adapt Settings to host the static doc-site 

Update: Actually we are doing a similar setup for pygeoapi.io website: https://github.com/geopython/pygeoapi.io. The 'Geonovum' site was based on that work :-).

**Comment by tomkralidis** [comment]
Implemented and live: https://dive.pygeoapi.io

We can integrate into https://pygeoapi.io proper once we are closer to this year's initial delivery at FOSS4G.

**Comment by tomkralidis** [comment]
Not sure what happened, but the custom domain on the Pages setup was unset. Resetting it seems to do the trick.

**Comment by justb4** [comment]
Strange, I was sure the custom domain https://dive.pygeoapi.io/ worked yesterday. But not anymore. It has disappeared from Settings|Pages. Maybe as easy as adding there, but @tomkralidis manages DNS. Or has the docs location changed. Ok, I now see some activity there....crossing actions...

**Comment by justb4** [comment]
It's back, closing..
