### ISSUE TITLE
create workshop agenda for FOSS4G Europe 2024

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#136]
An initial agenda has been put forth in https://github.com/geopython/diving-into-pygeoapi/wiki/Agenda-2024-07-02-FOSS4G-Europe

@doublebyte1 @pvgenuchten @justb4 @krishnaglodha @ldesousa to update.  We need at least two persons per section.

**Comment by tomkralidis** [comment]
2024-05-02:
- we still need to identify leads

**Comment by doublebyte1** [comment]
I did a PR [here](https://github.com/geopython/diving-into-pygeoapi/pull/147) to update the tiles section.

**Comment by pvgenuchten** [comment]
> * we still need to identify leads

Suggestion: first named to lead

**Comment by tomkralidis** [comment]
> Suggestion: first named to lead

Done
