### ISSUE TITLE
Exercise 2 - cptartu2.gpkg.zip is not available in repo

### ISSUE THREAD

**Issue by justb4** [geopython/diving-into-pygeoapi#149]
Exercise 2: the file https://github.com/geopython/diving-into-pygeoapi/tree/main/workshop/exercises/data/cptartu2.gpkg.zip is not in GH. Probably since GH default local action is not to commit/push .zip files. It can either be force-pushed. But the question is also how much storage is gained with zipping a GPKG file..

**Comment by tomkralidis** [comment]
@pvgenuchten we should upload only the GPKG in version control.

**Comment by justb4** [comment]
@pvgenuchten also in meeting came up: Exercise 2: should `bathingwater-estonia.*` data files be `swimming-water.*`? (or `drinking-water`?).

**Comment by pvgenuchten** [comment]
<img width="748" alt="image" src="https://github.com/geopython/diving-into-pygeoapi/assets/299829/c8476424-c4c2-48fb-b325-e3f196546177">
almost 50%

**Comment by justb4** [comment]
Ok, the GeoPackage are Cadastral Parcels. With ogr2ogr we can extract only area around conf building e.g. 
Some Linux systems don't have unzip by default.

**Comment by justb4** [comment]
Forget my last comment, we'll leave the zip as is.
