### ISSUE TITLE
Exercise 2 - updates for ES and Bathing Water and more

### ISSUE THREAD

**Issue by justb4** [geopython/diving-into-pygeoapi#150]
In Exercise 2: *Publish a GeoJSON using Elasticsearch* it states: 
`git checkout -b ogcapi-ws https://github.com/doublebyte1/pygeoapi.git` 
Why? Can we integrate [this dir](https://github.com/doublebyte1/pygeoapi/tree/ogcapi-ws/docker/examples/elastic) in this repo? Think ES example was there before. 

Also I doubt a bit if ES should immediately follow the GPKG exercise, maybe it is better in the "Advanced" section. 
I think it is more beneficial to start with the simplest: publish a CSV and then GeoJSON directly/natively (the "bathing water files", then move to GPKG and then as option ES. 
 
My feeling is that this will take quite some time to go through ES (download/start ES resolve issues etc). Let's discuss!

**Comment by tomkralidis** [comment]
- @justb4 to add starter example of GeoJSON/CSV
- leave ES exercise
- update pygeoapi ES repo pointer to https://github.com/geopython/pygeoapi-examples/tree/main/docker/elastic

**Comment by tomkralidis** [comment]
> * update pygeoapi ES repo pointer to https://github.com/geopython/pygeoapi-examples/tree/main/docker/elastic

Already done: https://github.com/geopython/diving-into-pygeoapi/tree/main/workshop/exercises/elastic

**Comment by justb4** [comment]
Overlooked: in https://dive.pygeoapi.io/publishing/first/  already treats publishing a CSV. So no need in Exercise 2. Can immediately treat publishing GPKG. I can slim it (see other issue). For ES will refer to `pygeoapi-examples`. 

Main question still: is is "Bathing Water" or "Drinking Water"? IMO the latter. Different translations for the same dataset are used and the filenames `bathingwater-estonia.*` should be changed.

* https://dive.pygeoapi.io/publishing/first/ "Bathing Water" (natural water to bathe and swim)
* https://dive.pygeoapi.io/publishing/ogcapi-tiles/#publish-pre-rendered-vector-tiles "Drinking Water"

Source: https://avaandmed.eesti.ee/datasets/joogiveeallikad where "Joogiveeallikad" translates to "Drinking Water Sources".

**Comment by justb4** [comment]
Ok, the confusion is: the data files are for bathing water, but the metadata links  for drinking water. Easiest is to change the Source/Metadata links to https://avaandmed.eesti.ee/datasets/supluskohad. Found via search on: https://avaandmed.eesti.ee/datasets?search=bathing.

PR upcoming.
