### ISSUE TITLE
ensure local data is demonstrated in each exercise

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#152]

**Comment by tomkralidis** [comment]
Done for Exercise 6/metadata in #153

**Comment by doublebyte1** [comment]
@justb4 Thank You! Addressed here: https://github.com/geopython/diving-into-pygeoapi/pull/160

**Comment by tomkralidis** [comment]
Outstanding:
- https://dive.pygeoapi.io/publishing/ogcapi-coverages/ (@krishnaglodha)
  - update link and have participants download as part of the exercise
