### ISSUE TITLE
Alternative for Workshop Matrix Channel?

### ISSUE THREAD

**Issue by justb4** [geopython/diving-into-pygeoapi#159]
Following the Gitter Link  on the Home page (under Support at bottom) or [README](https://github.com/geopython/diving-into-pygeoapi/blob/main/README.md).

https://matrix.to/#/#geopython_diving-into-pygeoapi:gitter.im

Personally, I find a setup with Matrix/Element etc, quite confusing. Gitter used to be linked to the repo as well.

An alternative is to use GitHub Discussions:
https://github.com/geopython/diving-into-pygeoapi/discussions

I propose to vote for GitHub Discussions (-1 means leave as is, use Matrix).

* @justb4 +1
*

**Comment by doublebyte1** [comment]
@justb4 you don't need to setup matrix/element in order to use gitter. I just follow the link and open it in a browser, using my GitHub user. 

https://app.gitter.im/#/room/#geopython_diving-into-pygeoapi:gitter.im

I updated the link in this PR: https://github.com/geopython/diving-into-pygeoapi/pull/161

**Comment by doublebyte1** [comment]
@justb4 Personally, I think the discussions do not have the same real-time feel as the chat apps, which is useful in synchronous events such as workshops.

**Comment by tomkralidis** [comment]
Agree with the real-time advantage of chat.

**Comment by pvgenuchten** [comment]
Gitter/matrix seems abandoned, or was it just me? telegram/discord seems to be the thing now. I like git discussions most, but agree it doesn’t give the same real time experience. What about osgeo discourse, could it be a basic alternative?

**Comment by tomkralidis** [comment]
Add link to gitter (#154) in reminder email (@tomkralidis).
