### ISSUE TITLE
create test data bundle

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#2]
Requirements
- vector data
  - e.g. GPKG, Shapefiles, GeoJSON
- raster data
  - GeoTIFF/COG, GRIB2, NetCDF
- metadata
  - ISO
  - OARec records

Considerations:
- local data (Florence/Italy) would be of value given FOSS4G 2022

cc @geopython/diving-into-pygeoapi-team

**Comment by PascalLike** [comment]
A GeoNetwork catalog full of data about Florence municipality that we could use:

http://dati.cittametropolitana.fi.it/geonetwork/srv/ita/catalog.search#/home

**Comment by tomkralidis** [comment]
As discussed, we will populate test data examples per section, pulling data/metadata from http://dati.cittametropolitana.fi.it/geonetwork/srv/ita/catalog.search#/home accordingly.  For metadata, we'll need to use pygeometa (ISO -> OARec record).

**Comment by doublebyte1** [comment]
We can reuse [these](https://github.com/geopython/diving-into-pygeoapi/tree/main/workshop/docker/data) datasets (or add more, on this folder!)
