### ISSUE TITLE
create workshop agenda

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#3]
Draft schedule/timing (time zone is in CEST):

- 13:30: team to meet to ensure no technical issues
- 14:00: start, welcome, workshop team introductions, schedule
- 14:10
  - introduction (@tomkralidis)
  - workshop environment setup (@justb4 / @PascalLike)
  - standards and building blocks (@doublebyte1 @tomkralidis)
- 15:10: 10 minute break
- 15:20
  - data publishing (NOTE: each subsection to demonstrate [client capability](https://github.com/geopython/diving-into-pygeoapi/issues/6) (QGIS, OpenLayers, Leaflet, Jupyter + OWSLib)
  - your first dataset (@pvgenuchten @just)
  - vector data (OGR, ArcGIS, ES): (@justb4 @pvgenuchten)
  - raster data (COG, GeoTIFF, GRIB2, NetCDF): (@francbartoli @kalxas)
- 16:35: 10 minute break
- 16:45
  - vector tiles (@doublebyte1 @francbartoli)
  - metadata: (@PascalLike @tomkralidis)
  - EDR (building block example? Publish one dataset using 2 APIs) (@tomkralidis @justb4)
  - conclusion (@tomkralidis)
- 18:00: close

**Comment by pvgenuchten** [comment]
Since we’re in Europe this time, should we add a chapter on implementing inspire with pygeoapi? (Ogc api records for discovery, ogc api features for download, ogc api tiles for view; one stop shop)

**Comment by tomkralidis** [comment]
Good idea.  What are the state/maturity levels of INSPIRE OGC API based standards?  Any docs/examples?

**Comment by pvgenuchten** [comment]
I created #11 to discuss the potential inspire topic

**Comment by tomkralidis** [comment]
As discussed today, given the audience, length of time and breadth of the content, we decided that we should cover until the client exercises.  All following sections will be part of the content, to which advanced users can work through.

**Comment by tomkralidis** [comment]
- have each data publishing subsection showing 1..n clients (vs. showing all at the end)

**Comment by tomkralidis** [comment]
- laptop sharing We will use [Jitsi](https://meet.jit.si/diving-into-pygeoapi)
- swag: hand out at end of workshop

**Comment by doublebyte1** [comment]
Maybe we can also advertise the [upcoming code sprint](https://developer.ogc.org/sprints/18/), if anyone is interested in OAR (:

**Comment by tomkralidis** [comment]
Good point @doublebyte1. This is now communicated in the conclusion.

**Comment by tomkralidis** [comment]
Final agenda now posted to https://github.com/geopython/diving-into-pygeoapi/wiki/Agenda-2022-08-22-FOSS4G
