### ISSUE TITLE
Decide on Docker Compose command

### ISSUE THREAD

**Issue by justb4** [geopython/diving-into-pygeoapi#42]
Heads up: Docker Compose is [now part of the Docker CLI.](https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command) since Docker Desktop 3.2.1. But worse the command has changed: i.s.o. `docker-compose` it is `docker compose` (space i.s.o. hyphen).
I think it appears in Ubuntu 22.04, but not in Ubuntu 20.04 and not in older Docker Desktop for Mac versions. You can try your status by typing:
`docker compose version` (not `--version`). You either get a version like v2.2.1 or *docker: 'compose' is not a docker command.*.

So what to do? It is still possible to install `docker-compose` via pip (v1.29). We tried using `alias` yesterday but that became messy.

I suggest using `docker-compose`.

**Comment by pvgenuchten** [comment]
I like how it is solved now just; a note for users using the new docker version, suggest to close
