### ISSUE TITLE
Minor editorial issues tiles exercise/config

### ISSUE THREAD

**Issue by justb4** [geopython/diving-into-pygeoapi#48]
@doublebyte1 Went through the exercise, all working, QGIS, Leaflet etc.! Two minor editorials:

* tiles.md L106: `the{tileMatrix}/{tileRow}/{tileCol} by {x}/{x}/{y}`. must be `the{tileMatrix}/{tileRow}/{tileCol} by {z}/{x}/{y}.`
* docker.config.yml `Cycles` Collection: setting `id_field: accicid` worked for me

**Comment by tomkralidis** [comment]
Fixed in forthcoming changes as part of `editorial-updates-2022-08-08` once over branch.
