### ISSUE TITLE
Is pygeoapi a geoserver, a library or a microservice

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/diving-into-pygeoapi#49]
Probably the answer is yes to all of these, should we dedicate a page on the tutorial or some intro slides on answering this question, with practical examples?

**Comment by tomkralidis** [comment]
Good point.  pygeoapi is a Geospatial Web API server which is cloud native and supports microservices.

**Comment by pvgenuchten** [comment]
So it is not intended to be also a library, for others to build geospatial api’s on top?

**Comment by tomkralidis** [comment]
Sure, we can call it a library and/framework to deploy using a Python web framework of choice, and/or integration into an existing API.

**Comment by pvgenuchten** [comment]
Aim of the issue was to create some samples of either use case, but other tasks are more urgent, closing this
