### ISSUE TITLE
decide on chatroom

### ISSUE THREAD

**Issue by tomkralidis** [geopython/diving-into-pygeoapi#5]
As discussed on 2022-05-20, options:
- existing pygeoapi Gitter https://gitter.im/geopython/pygeoapi
- new Gitter specific to the workshop (i.e. would be https://gitter.im/geopython/diving-into-pygeoapi)

Considerations:
- all of the workshop delivery team is already on/using the existing pygeoapi Gitter
- then again, having a dedicated workshop Gitter would keep conversations focused

Thoughts?

cc @geopython/diving-into-pygeoapi-team

**Comment by pvgenuchten** [comment]
Is this a vote?
Then I vote for option B (mainly to not having to search for things related to training in main thread)

**Comment by francbartoli** [comment]
+1 for a dedicated Gitter channel

**Comment by tomkralidis** [comment]
Room created at https://gitter.im/geopython/diving-into-pygeoapi

**Comment by tomkralidis** [comment]
Test Gitter integration.
