### ISSUE TITLE
Demo/Exercise various ogc api clients

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/diving-into-pygeoapi#6]
# An inventarisation of existing clients

OGC API Features
- https://gdal.org/drivers/vector/oapif.html
- https://geopython.github.io/OWSLib/usage.html#ogc-api (+jupyter)
- https://github.com/openlayers/openlayers/issues/12387
- https://docs.qgis.org/3.22/en/docs/server_manual/services/ogcapif.html
- https://github.com/opengeospatial/ogcapi-features/blob/master/implementations/clients/leaflet.md
- https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-OGCFeatureLayer.html

OGC API Records
- https://github.com/qgis/QGIS/pull/44812

OGC API Tiles
- https://openlayers.org/en/latest/examples/ogc-vector-tiles.html
- https://openlayers.org/en/latest/examples/ogc-map-tiles.html
- https://blog.ianturton.com/ogc/geotools/2020/05/03/ogc-api-sprint.html

OGC API Coverages
- GDAL - https://gdal.org/drivers/raster/ogcapi.html

STAC/COG
- https://github.com/stac-utils/qgis-stac-plugin
- https://github.com/stac-utils/pystac-client
- https://github.com/radiantearth/stac-browser

SPARQL (evaluate if json-ld has been properly configured)
- https://jena.apache.org/documentation/query/cmds.html

## Suggestions for exercises

- QGIS; 
  - query a ogc-api-records catalogue (would be nice to be able to open a map service from a record, status?)
  - add a ogc-api features layer
- OpenLayers; 
  - Add a ogc-api-tiles layer; 
  - Add a ogc-api-Features layer;
- GDAL
  - connect to a ogc api features service (ogrinfo; ogr2ogr)
  - connect to a ogc api coverages service (gdalinfo)

**Comment by doublebyte1** [comment]
> OGC API Tiles
> 
> * https://openlayers.org/en/latest/examples/ogc-vector-tiles.html

@pvgenuchten  unfortunately this does not work with the current pygeoapi implementation

**Comment by justb4** [comment]
> > OGC API Tiles
> > 
> > * https://openlayers.org/en/latest/examples/ogc-vector-tiles.html
> 
> @pvgenuchten unfortunately this does not work with the current pygeoapi implementation

Yes, I just noticed, trying our https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad/metadata?f=json in that example. Think has to do with JSON (in OL example (?)) vs TileJSON (supported by pygeoapi I think) and possibly some metadata from pygeoapi that OL does not like. Hard to  debug. Tried that same example with `ol.source.TileJSON` i.s.o. `ol.source.OGCVectorTile`. But also got errors. But I am not well-versed in OL Vector Tiles. Maybe it is something simple that `pygeoapi` needs to set in the metadata, or support both JSON and TileJSON...

**Comment by justb4** [comment]
Possibly it will work in OpenLayers when using an 'x,y,z' URL like http://localhost:5000/collections/Cycle/tiles/WorldCRS84Quad/{z}/{x}/{y}?f=mvt, see the [Leaflet](https://github.com/geopython/diving-into-pygeoapi/blob/main/workshop/html/vector-tiles.html) QGIS examples.

**Comment by pvgenuchten** [comment]
that's unfortunate to hear, so this has not been tested before, i wonder with which server openlayers has been testing this

**Comment by justb4** [comment]
Well, to find out, one can either run OL in JS debugger, and/or compare 
https://maps.ecere.com/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries?f=json with a `pygeoapi` endpoint line by line.

**Comment by pvgenuchten** [comment]
content is moved to the publish section, per standard
