### ISSUE TITLE
Mixing yaml and xml?

### ISSUE THREAD

**Issue by Delawen** [geopython/diving-into-pygeoapi#76]
Not sure if a bug or just a weird way of configuring things but when I am at the end of the `Workshop environment setup` (http://127.0.0.1:8000/diving-into-pygeoapi/setup/), there is this suspicious line:

`-v $(pwd)/default.config.yml:/pygeoapi/pygeoapi-config.xml ` which replaces an xml with a yaml file

Which is immediately overrided by `-e PYGEOAPI_CONFIG=/pygeoapi/pygeoapi-config.yml` (if I understood this right).

The full command is 

```
docker run -p 5000:80 \    -v $(pwd)/data:/pygeoapi/mydata \
    -v $(pwd)/default.config.yml:/pygeoapi/pygeoapi-config.xml \
    -e PYGEOAPI_CONFIG=/pygeoapi/pygeoapi-config.yml \
    geopython/pygeoapi:latest
```

(also copy/pasting this directly from the browser, at least on Firefox, ignores the first new line which makes the first `\` character useless)

**Comment by tomkralidis** [comment]
@Delawen this should now be fixed.  Can you validate?
