### ISSUE TITLE
Different syntax for mounting pwd on windows

### ISSUE THREAD

**Issue by jvdkwast** [geopython/diving-into-pygeoapi#81]
In the section *Workshop environment setup* the command to run the container with overridden config file is different for windows.
See [https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10](https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10).

In the PowerShell the command is:
`docker run -p 5000:80 -v ${PWD}/default.config.yml:/pygeoapi/local.config.yml geopython/pygeoapi:latest`

**Comment by tomkralidis** [comment]
Thanks @jvdkwast.  Updated documentation.
